{{/*
SPDX-FileCopyrightText: 2026 The IndustryFlow contributors
SPDX-License-Identifier: AGPL-3.0-or-later
*/}}

{{- define "industryflow.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "industryflow.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name (include "industryflow.name" .) | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "industryflow.labels" -}}
app.kubernetes.io/part-of: industryflow
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
{{- end -}}

{{/*
Compose a first-party image reference, preferring an immutable digest over the mutable tag.
Call with a dict: registry, image, tag, digest. When `digest` is set it wins (registry/image@sha256:…)
and the tag is ignored; otherwise falls back to registry/image:tag (dev default). Production
overlays (values-digests.yaml, generated by scripts/pin-image-digests.sh) supply the digests.
*/}}
{{- define "industryflow.image" -}}
{{- if .digest -}}
{{- printf "%s/%s@%s" .registry .image .digest -}}
{{- else -}}
{{- printf "%s/%s:%s" .registry .image .tag -}}
{{- end -}}
{{- end -}}

{{/* Legacy single-secret name (kept for the existingSecret fallback). */}}
{{- define "industryflow.secretName" -}}
{{- if .Values.secrets.existingSecret -}}
{{- .Values.secrets.existingSecret -}}
{{- else -}}
{{- printf "%s-secrets" (include "industryflow.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Per-workload scoped Secret name. Call with a dict: ctx (root context), workload (string).
When secrets.existingSecret is set, every workload references that one Secret (the operator
scopes at their backend); otherwise each workload gets its own `<fullname>-<workload>-secrets`.
*/}}
{{- define "industryflow.workloadSecretName" -}}
{{- $ctx := .ctx -}}
{{- if $ctx.Values.secrets.existingSecret -}}
{{- $ctx.Values.secrets.existingSecret -}}
{{- else -}}
{{- printf "%s-%s-secrets" (include "industryflow.fullname" $ctx) .workload -}}
{{- end -}}
{{- end -}}

{{/*
Render a scoped Opaque Secret for one workload. Call with a dict: ctx, workload, keys (list).
Each key's value is selected from .Values.secrets.data, so the master map stays the single
source of values while each workload's Secret carries only the keys it needs.
*/}}
{{- define "industryflow.scopedSecret" -}}
{{- $ctx := .ctx -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "industryflow.workloadSecretName" (dict "ctx" $ctx "workload" .workload) }}
  labels:
    {{- include "industryflow.labels" $ctx | nindent 4 }}
    app.kubernetes.io/name: {{ .workload }}
type: Opaque
stringData:
{{- range $k := .keys }}
  {{ $k }}: {{ index $ctx.Values.secrets.data $k | quote }}
{{- end }}
{{- end -}}

{{/* Resolve the TimescaleDB host: in-cluster service name or external host. */}}
{{- define "industryflow.dbHost" -}}
{{- if .Values.infra.timescaledb.inCluster -}}
{{- printf "%s-timescaledb" (include "industryflow.fullname" .) -}}
{{- else -}}
{{- required "infra.timescaledb.external.host is required when inCluster=false" .Values.infra.timescaledb.external.host -}}
{{- end -}}
{{- end -}}

{{/* Resolve the Kafka bootstrap servers. */}}
{{- define "industryflow.kafkaBootstrap" -}}
{{- if .Values.infra.kafka.inCluster -}}
{{- printf "%s-kafka:%v" (include "industryflow.fullname" .) .Values.infra.kafka.port -}}
{{- else -}}
{{- required "infra.kafka.external.bootstrap is required when inCluster=false" .Values.infra.kafka.external.bootstrap -}}
{{- end -}}
{{- end -}}

{{/* Resolve the Redis host. */}}
{{- define "industryflow.redisHost" -}}
{{- if .Values.infra.redis.inCluster -}}
{{- printf "%s-redis" (include "industryflow.fullname" .) -}}
{{- else -}}
{{- required "infra.redis.external.host is required when inCluster=false" .Values.infra.redis.external.host -}}
{{- end -}}
{{- end -}}

{{/* Resolve the MinIO endpoint (host:port). */}}
{{- define "industryflow.minioEndpoint" -}}
{{- if .Values.infra.minio.inCluster -}}
{{- printf "http://%s-minio:%v" (include "industryflow.fullname" .) .Values.infra.minio.apiPort -}}
{{- else -}}
{{- required "infra.minio.external.endpoint is required when inCluster=false" .Values.infra.minio.external.endpoint -}}
{{- end -}}
{{- end -}}

{{/* Resolve the MLflow tracking URI. */}}
{{- define "industryflow.mlflowUri" -}}
{{- if .Values.infra.mlflow.inCluster -}}
{{- printf "http://%s-mlflow:%v" (include "industryflow.fullname" .) .Values.infra.mlflow.port -}}
{{- else -}}
{{- required "infra.mlflow.external.trackingUri is required when inCluster=false" .Values.infra.mlflow.external.trackingUri -}}
{{- end -}}
{{- end -}}
