# SPDX-FileCopyrightText: 2026 The IndustryFlow contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""
The cold layer's Parquet encoding contract, across a pyarrow upgrade (ADR-0025 dec 1, dec 3).

Once retention drops the source chunk, the Parquet file is the ONLY copy of that history — so a
pyarrow upgrade is a data-durability question, not a lint. Two properties have to survive one:

  * OLD FILES STILL READ. `fixtures/cold_pyarrow14.parquet` was written by the pyarrow the exporter
    was pinned to before the numpy-2 bump (14.0.1), using this exact schema and writer settings. It
    is checked in as a byte-for-byte artefact precisely so it cannot be regenerated by the pyarrow
    under test — a fixture the current writer produced would prove nothing about reading history.

  * NEW FILES ARE ENCODED THE SAME WAY. The writer states its format version and compression
    (store.PARQUET_*) instead of inheriting a library default that an upgrade could move, and the
    footer is asserted to agree.

`parquet_row_count` reads the footer for exactly one reason: it is the verification that gates the
chunk drop (dec 3). A reader that could not open an old file, or a footer whose row count did not
survive, is how the cold layer silently loses history.
"""
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq
import pytest

from cold_export.source import COLD_SCHEMA
from cold_export.store import PARQUET_COMPRESSION, PARQUET_FORMAT_VERSION

# Written by pyarrow 14.0.1 / numpy 1.26.4 — the pins in place before the numpy-2 bump.
LEGACY_FIXTURE = Path(__file__).parent / "fixtures" / "cold_pyarrow14.parquet"
LEGACY_ROWS = 5
LEGACY_VALUES = [20.0, 21.0, 22.0, 23.0, 24.0]


def _batch(rows: int) -> pa.RecordBatch:
    """A batch shaped exactly like the one source.PostgresMeasurementSource yields."""
    start = datetime(2026, 1, 15, 6, 0, tzinfo=timezone.utc)
    return pa.record_batch(
        [
            pa.array([start + timedelta(minutes=i) for i in range(rows)],
                     type=COLD_SCHEMA.field("time").type),
            pa.array([f"sensor-{i}" for i in range(rows)], type=pa.string()),
            pa.array(["equip-1"] * rows, type=pa.string()),
            pa.array(["site-1"] * rows, type=pa.string()),
            pa.array([20.0 + i for i in range(rows)], type=pa.float64()),
            pa.array(["C"] * rows, type=pa.string()),
            pa.array([1] * rows, type=pa.int32()),
            pa.array([False] * rows, type=pa.bool_()),
        ],
        schema=COLD_SCHEMA,
    )


def test_legacy_parquet_still_reads():
    """A file written by the pre-upgrade pyarrow opens, and its content is unchanged."""
    table = pq.read_table(LEGACY_FIXTURE)

    assert table.schema.equals(COLD_SCHEMA), "the cold schema shifted under a pyarrow upgrade"
    assert table.num_rows == LEGACY_ROWS
    assert table.column("value").to_pylist() == LEGACY_VALUES
    assert table.column("is_anomaly").to_pylist() == [False, False, True, False, False]
    assert str(table.column("time")[0]) == "2026-01-15 06:00:00+00:00"


def test_legacy_parquet_footer_row_count_survives():
    """The footer count is what gates the chunk drop (dec 3) — it must read off an old file."""
    assert pq.ParquetFile(LEGACY_FIXTURE).metadata.num_rows == LEGACY_ROWS


def test_legacy_parquet_was_written_by_the_old_pyarrow():
    """Guard the fixture itself: regenerating it under the new pyarrow would void both tests above."""
    created_by = pq.ParquetFile(LEGACY_FIXTURE).metadata.created_by
    assert "14.0.1" in created_by, (
        f"fixture was rewritten by {created_by!r} — it must stay the artefact of the OLD pyarrow, "
        "or it no longer proves that history written before the upgrade still reads"
    )


def test_new_writes_keep_the_encoding_contract(tmp_path):
    """What the exporter writes today carries the same format version and codec as the old files."""
    out = tmp_path / "new.parquet"
    batch = _batch(3)
    with pq.ParquetWriter(out, batch.schema,
                          compression=PARQUET_COMPRESSION, version=PARQUET_FORMAT_VERSION) as w:
        w.write_batch(batch)

    new_md = pq.ParquetFile(out).metadata
    legacy_md = pq.ParquetFile(LEGACY_FIXTURE).metadata

    assert new_md.format_version == legacy_md.format_version == PARQUET_FORMAT_VERSION
    assert new_md.row_group(0).column(0).compression == PARQUET_COMPRESSION.upper()
    assert pq.read_table(out).schema.equals(COLD_SCHEMA)


@pytest.mark.parametrize("column, index", [("time", 0), ("equipment_id", 2)])
def test_row_group_statistics_are_written(column, index, tmp_path):
    """Dec 6 leans on min/max stats to skip blocks; an encoding change that dropped them is a regression."""
    out = tmp_path / "stats.parquet"
    batch = _batch(3)
    with pq.ParquetWriter(out, batch.schema,
                          compression=PARQUET_COMPRESSION, version=PARQUET_FORMAT_VERSION) as w:
        w.write_batch(batch)

    stats = pq.ParquetFile(out).metadata.row_group(0).column(index).statistics
    assert stats is not None and stats.has_min_max, f"no min/max statistics for {column}"
