#!/bin/sh
# SPDX-FileCopyrightText: 2026 The IndustryFlow contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Resolve the immutable digests of the first-party IndustryFlow images for a given tag and
# emit a Helm values overlay that pins each by digest (ADR-0009).
#
# First-party image digests rotate on every build, so they are NOT hand-maintained in
# values.yaml — values.yaml ships `digest: ""` (use the mutable tag, the dev default) and a
# digest, when present, wins. This script generates the production overlay:
#
#   scripts/pin-image-digests.sh latest > deploy/helm/industryflow/values-digests.yaml
#   helm upgrade --install if deploy/helm/industryflow -f values-digests.yaml
#
# Resolution uses the registry HTTP API (no docker/skopeo/crane needed). For private GHCR
# packages, authenticate via `gh auth token` (preferred) or the GITHUB_TOKEN env var; public
# packages resolve anonymously.
#
# Usage:  pin-image-digests.sh [TAG]                 (TAG defaults to "latest")
# Env:    REGISTRY  registry/namespace prefix         (default: ghcr.io/iichukissii)
#         GITHUB_TOKEN  PAT for private package pulls  (else falls back to `gh auth token`)

set -eu

TAG="${1:-latest}"
REGISTRY="${REGISTRY:-ghcr.io/iichukissii}"

# Split REGISTRY into host (ghcr.io) and namespace (iichukissii). Only GHCR is supported as the
# first-party registry today; extend the token logic below for other registries if that changes.
REG_HOST="${REGISTRY%%/*}"
REG_NS="${REGISTRY#*/}"
if [ "$REG_HOST" != "ghcr.io" ]; then
  echo "error: only ghcr.io is supported for first-party digests (got '$REG_HOST')" >&2
  exit 2
fi

# value-path : image-name pairs — one per first-party image the chart deploys. Keep in sync
# with values.yaml (apps.*, infra.mlflow, notebookHub.hub). Format: "<yaml-path>=<image>".
IMAGES="
apps.api-gateway=industryflow-api-gateway
apps.ml-service-api=industryflow-ml-service-api
apps.alert-service-api=industryflow-alert-service-api
apps.alert-service-detector=industryflow-alert-service-detector
apps.ingestion-service=industryflow-ingestion-service
apps.spark-streaming=industryflow-spark-streaming
apps.spark-aggregations=industryflow-spark-aggregations
apps.frontend=industryflow-frontend
infra.mlflow=industryflow-mlflow
notebookHub.hub=industryflow-notebook-hub
"

# Credentials for private GHCR packages (optional for public ones).
PAT="${GITHUB_TOKEN:-}"
if [ -z "$PAT" ] && command -v gh >/dev/null 2>&1; then
  PAT="$(gh auth token 2>/dev/null || true)"
fi

# Resolve one image's manifest-list (multi-arch) digest via the registry v2 API.
resolve() {
  image="$1"
  repo="${REG_NS}/${image}"
  auth=""
  [ -n "$PAT" ] && auth="$(printf '%s' "$PAT" | base64 | tr -d '\n')"

  if [ -n "$auth" ]; then
    token="$(curl -fsS -H "Authorization: Bearer ${auth}" \
      "https://ghcr.io/token?service=ghcr.io&scope=repository:${repo}:pull" | jq -r .token)"
  else
    token="$(curl -fsS \
      "https://ghcr.io/token?service=ghcr.io&scope=repository:${repo}:pull" | jq -r .token)"
  fi

  curl -fsSI \
    -H "Authorization: Bearer ${token}" \
    -H "Accept: application/vnd.oci.image.index.v1+json" \
    -H "Accept: application/vnd.docker.distribution.manifest.list.v2+json" \
    -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
    "https://ghcr.io/v2/${repo}/manifests/${TAG}" \
    | tr -d '\r' | awk -F': ' 'tolower($1)=="docker-content-digest"{print $2}'
}

# Emit the overlay. Nesting mirrors values.yaml so `-f` merges cleanly.
echo "# SPDX-FileCopyrightText: 2026 The IndustryFlow contributors"
echo "# SPDX-License-Identifier: AGPL-3.0-or-later"
echo "#"
echo "# GENERATED by scripts/pin-image-digests.sh — do not edit by hand."
echo "# First-party image digests for tag '${TAG}' from ${REGISTRY}. Apply with: -f values-digests.yaml"
echo "apps:"
printf '%s\n' "$IMAGES" | while IFS='=' read -r path image; do
  [ -z "$path" ] && continue
  case "$path" in apps.*) ;; *) continue ;; esac
  name="${path#apps.}"
  digest="$(resolve "$image")"
  [ -z "$digest" ] && { echo "error: no digest for ${image}:${TAG}" >&2; exit 1; }
  printf '  %s:\n    digest: "%s"\n' "$name" "$digest"
done
echo "infra:"
printf '%s\n' "$IMAGES" | while IFS='=' read -r path image; do
  case "$path" in infra.*) ;; *) continue ;; esac
  name="${path#infra.}"
  digest="$(resolve "$image")"
  [ -z "$digest" ] && { echo "error: no digest for ${image}:${TAG}" >&2; exit 1; }
  printf '  %s:\n    digest: "%s"\n' "$name" "$digest"
done
echo "notebookHub:"
printf '%s\n' "$IMAGES" | while IFS='=' read -r path image; do
  case "$path" in notebookHub.*) ;; *) continue ;; esac
  name="${path#notebookHub.}"
  digest="$(resolve "$image")"
  [ -z "$digest" ] && { echo "error: no digest for ${image}:${TAG}" >&2; exit 1; }
  printf '  %s:\n    digest: "%s"\n' "$name" "$digest"
done
